name: Shell

on:
  pull_request:
    paths:
      - .github/workflows/shell.yml
      - '**/*.sh'

permissions:
  contents: read

jobs:
  # For more information on shellcheck failures:
  # https://github.com/koalaman/shellcheck/wiki/Checks
  shellcheck:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    steps:
      - uses: linkerd/dev/actions/setup-tools@v36
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
      - run: just sh-lint

